vostpt/covid19-mobile

- analysis_options.yaml
- lib/generated/intl/messages_all.dart
- lib/generated/intl/messages_en.dart
- lib/generated/l10n.dart
- lib/model/api_response_model.dart
- lib/resources/constants.dart
- lib/services/api_service.dart
- test/unit/mocks.dart
- Removes some rules;
- Fixes some linter recommendations;
- Formats project to match Flutter guidelines;
Closes #53.
> Update static options (#53)

- lib/bloc/app_bloc.dart
- lib/bloc/base_bloc.dart
- lib/model/api_response_model.dart
- lib/model/stats_model.dart
- lib/model/stats_model.g.dart
- lib/providers/stats_provider.dart
- lib/services/api.dart
- lib/services/api_service.dart
- lib/ui/app.dart
- lib/ui/core/base_stream_service_screen_page.dart
- lib/ui/screens/home/home_page.dart
- test/unit/api_test.dart
API get Stats
Added mock API test get stats
closes #17
> api get stats

- lib/model/api_response_model.dart
- lib/resources/constants.dart
> fix api response model constant import

- lib/bloc/app_bloc.dart
- lib/bloc/base_bloc.dart
- lib/main.dart
- lib/model/base_post_model.dart
- lib/model/stats_model.dart
- lib/providers/stats_provider.dart
- lib/services/api.dart
- lib/services/api_service.dart
- lib/ui/app.dart
- lib/ui/core/base_stream_service_screen_page.dart
- lib/ui/screens/home/home_page.dart
- test/unit/api_test.dart
- test/unit/mocks.dart
- test/widget/test_widget.dart
Closes #72
Adds base post model
:white_check_mark: Models 
:white_check_mark: Dartfmt @ root
>  #72 - Improvement - Create Generic Post Model

- ios/Podfile.lock
- lib/bloc/app_bloc.dart
- lib/bloc/base_bloc.dart
- lib/main.dart
- lib/model/base_post_model.dart
- lib/model/post_type.dart
- lib/model/remote_work_model.dart
- lib/model/remote_work_model.g.dart
- lib/model/stats_model.dart
- lib/providers/remote_work_provider.dart
- lib/providers/stats_provider.dart
- lib/services/api.dart
- lib/services/api_service.dart
- lib/ui/app.dart
- lib/ui/core/base_stream_service_screen_page.dart
- lib/ui/screens/home/home_page.dart
- pubspec.lock
- test/unit/api_test.dart
- test/unit/mocks.dart
- test/widget/test_widget.dart
WIP #59 
Created all classes needed to have the endpoint to grab RemoteWork Posts information.
:white_check_mark: Models 
:white_check_mark: ModelProvider
:: Tests 
:: Dartfmt @ root
> API posts to get RemoteWork posts

- ios/Podfile.lock
- lib/bloc/app_bloc.dart
- lib/bloc/base_bloc.dart
- lib/main.dart
- lib/model/base_post_model.dart
- lib/model/measures_model.dart
- lib/model/measures_model.g.dart
- lib/model/post_type.dart
- lib/model/remote_work_model.dart
- lib/model/remote_work_model.g.dart
- lib/model/stats_model.dart
- lib/providers/measures_provider.dart
- lib/providers/remote_work_provider.dart
- lib/providers/stats_provider.dart
- lib/services/api.dart
- lib/services/api_service.dart
- lib/ui/app.dart
- lib/ui/core/base_stream_service_screen_page.dart
- lib/ui/screens/home/home_page.dart
- lib/ui/widgets/card_files_link.dart
- lib/ui/widgets/statistics_number_big.dart
- pubspec.lock
- pubspec.yaml
- test/unit/api_test.dart
- test/unit/mocks.dart
- test/widget/test_widget.dart
Closes #58 
Created all classes needed to have the endpoint to grab Measures information.
:white_check_mark: Models 
:white_check_mark: ModelProvider
:white_check_mark: Tests 
:white_check_mark: Dartfmt @ root
> Task/#58 add API measures

- lib/bloc/app_bloc.dart
- lib/model/faq_model.dart
- lib/model/faq_model.g.dart
- lib/model/measures_model.g.dart
- lib/providers/faq_provider.dart
- lib/resources/style/text_styles.dart
- lib/ui/screens/home/home_page.dart
- test/unit/api_test.dart
- test/unit/models_test.dart
- test/widget/widget_test.dart
- test/widget/widget_test_utils.dart
Closes #90
Adds field `entidade _responsável`
:white_check_mark: Update Model
:white_check_mark: Update Tests
:white_check_mark: Dartfmt @ root
> #90 - Adds Responsable Entity Model

- lib/ui/widgets/header_main.dart
Widget proposal for Header_Main
Not sure what to do, let me know what you think.
closes #24
> 24 header main

- lib/ui/app.dart
- lib/ui/screens/home/components/card_home.dart
- lib/ui/screens/home/home_page.dart
- lib/ui/widgets/button_background.dart
Added card for home that accepts `String` title and `VoidCallback`
> #98 Card Home

- lib/ui/screens/home/home_page.dart
- lib/ui/widgets/button_border_background.dart
- lib/ui/widgets/card_border_arrow.dart
closes #102 
* Adds Bordered Background
* Adds bordered button with callback
> #102 Adds Bordered Button

- analysis_options.yaml
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/vost/covidtriage/covid19-mobile/Application.kt
- android/build.gradle
- ios/Podfile.lock
- lib/main.dart
- lib/services/messaging_service.dart
- lib/ui/app.dart
- pubspec.lock
- pubspec.yaml
Setups FCM on both iOS & Android to register for push notifications.
Closes #9.
> Firebase Messaging (#9)

- lib/resources/style/themes.dart
- lib/ui/assets/dimensions.dart
- lib/ui/widgets/header_tabs.dart
Widget for Header Tabs
https://youtu.be/rMXW3MHacHo
closes #23
> 23 header tabs

- lib/generated/intl/messages_en.dart
- lib/generated/l10n.dart
- lib/l10n/intl_en.arb
- lib/resources/constants.dart
- lib/resources/style/themes.dart
- lib/ui/app.dart
- lib/ui/screens/home/home_page.dart
- lib/ui/screens/remote_work/remote_work_page.dart
- lib/ui/screens/remote_work_details/remote_work_details.dart
- pubspec.lock
- pubspec.yaml
> #122 Adds Remote Work

- lib/ui/widgets/initiatives_item.dart
> Creates initiatives item

- lib/ui/screens/about/about_page.dart
> hide report from about page

- lib/ui/screens/remote_work_details/remote_work_details.dart
Adds launchUrl do urls in Remote Work
> Add clickable URLS in Remote Work

- lib/ui/screens/home/components/statistics_button.dart
- lib/ui/screens/video_player/video_player_page.dart
- lib/ui/widgets/initiatives_item.dart
Adds back button to video player
Adds correct callback to statistics button
Adds richtext to initiatives
> Misc Fixes

- assets/licence.txt
- lib/generated/intl/messages_en.dart
- lib/generated/l10n.dart
- lib/l10n/intl_en.arb
- lib/resources/constants.dart
- lib/ui/app.dart
- lib/ui/screens/about/about_page.dart
- lib/ui/screens/about/licences_page.dart
- lib/ui/screens/faqs/faqs_page.dart
- pubspec.lock
- pubspec.yaml
> adds licenses page

- lib/model/video_model.dart
- lib/ui/screens/videos/videos_page.dart
closes #153 
From the video id, generates the thumbnail url
> #153 - Adds video thumbnail from id

- lib/ui/screens/statistics/statistics_page.dart
> #149 Fixes Statistics Page boxes height

- lib/resources/icons_svg.dart
- lib/ui/screens/contacts/contacts_page.dart
- lib/ui/screens/home/components/card_home.dart
- lib/ui/screens/home/components/statistics_button.dart
- lib/ui/screens/home/home_page.dart
- lib/ui/widgets/card_border_arrow.dart
closes #145 
* Adds correct icon to home arrows
* Removes bottom margin from home
* Puts home logo in scrollview
**Screenshot**
> UI Fixes for Home

- lib/bloc/base_bloc.dart
- lib/generated/intl/messages_all.dart
- lib/generated/intl/messages_en.dart
- lib/generated/l10n.dart
- lib/resources/icons_svg.dart
- lib/ui/screens/about/about_page.dart
- lib/ui/screens/about/licences_page.dart
- lib/ui/screens/contacts/components/contact_card.dart
- lib/ui/screens/contacts/contacts_page.dart
- lib/ui/screens/home/home_page.dart
- lib/ui/widgets/card_border_arrow.dart
- lib/ui/widgets/initiatives_item.dart
Closes #147 
- Website icon looks small: improved icon size
- Padding is incorrect: improved padding
- Card doesn't have rounded border: adds rounded border to the card
extra: adds color feedback on tap
✅ dartfmt @ root
> misc fixes for contacts view

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- lib/ui/app.dart
- lib/ui/assets/dimensions.dart
- lib/ui/screens/video_player/video_player_page.dart
- lib/ui/screens/videos/videos_page.dart
Added fixed orientation on application start
Removes fixed orientation on VideosPage
Adds fixed orientation on VideosPage dispose
possibly closes #156
> 156 fix portrait orientation for app and all for videos

- lib/bloc/app_bloc.dart
- lib/bloc/base_bloc.dart
- lib/model/post_type.dart
- lib/model/slider_model.dart
- lib/model/slider_model.g.dart
- lib/providers/slider_provider.dart
- lib/ui/assets/colors.dart
- lib/ui/screens/home/components/card_home_slider.dart
- lib/ui/screens/home/components/card_home_slider_indicator.dart
- lib/ui/screens/home/home_page.dart
Closes #171 
- Adds Home Card Slider with indicator
- Loads Slider data from API into Widget
✅ dartfmt @ root
> adds home slider

- lib/bloc/app_bloc.dart
- lib/bloc/base_bloc.dart
- lib/providers/faq_provider.dart
- lib/services/api_service.dart
- lib/ui/screens/faqs/faqs_page.dart
- lib/ui/screens/home/home_page.dart
- test/provider/faq_provider_test.dart
closes #168 
* Fetches Faqs for each category
* Updates Provider to have a Map with the `id` as a key
* Changes Endpoints to Production
> #168 Update Faqs Endpoint

- ios/Podfile.lock
- lib/main.dart
- lib/model/post_type.dart
- lib/model/video_model.dart
- lib/model/video_model.g.dart
- lib/services/api_service.dart
- test/unit/api_test.dart
* Adds configuration for Dev and PROD
* Changes IDs for initiatives
* Changes Endpoint
> Add configurations for dev and prod

- lib/ui/screens/home/components/card_home_slider.dart
* Removes title
* Removes button
* Removes overlay
* Adds shadow
**Screenshot**
> Changes Slider UI

- lib/bloc/app_bloc.dart
- lib/bloc/base_bloc.dart
- lib/providers/faq_provider.dart
- lib/ui/screens/faqs/faqs_page.dart
- lib/ui/screens/splash/splash_page.dart
- test/provider/faq_provider_test.dart
* Adds missing `FaqsResultStream` listener to splash and faqs page
> Fix faqs not showing

- lib/ui/screens/about/about_page.dart
- lib/ui/screens/faqs/faqs_page.dart
- lib/ui/screens/faqs_details/faq_details_page.dart
- lib/ui/screens/home/components/card_home.dart
- lib/ui/screens/home/components/card_video.dart
- lib/ui/screens/home/components/statistics_button.dart
- lib/ui/screens/measures/measures_extensions.dart
- lib/ui/screens/measures/measures_page.dart
- lib/ui/screens/statistics/statistics_page.dart
My proposal this fix, replaces space with new line.
Also added a new line at the end of the first column, so that they would be aligned (includes logic in case switches to 2 words).
Added launURL for the ESRI text
Added license to some files
Moved import order on some files
Possibly closes #194
> 194 ui fixes statistics

- lib/bloc/base_bloc.dart
- lib/main.dart
- lib/providers/faq_provider.dart
- lib/resources/style/themes.dart
- lib/ui/app.dart
- lib/ui/screens/about/about_page.dart
- lib/ui/screens/faqs/faqs_page.dart
- lib/ui/screens/faqs_details/faq_details_page.dart
- lib/ui/screens/home/components/accordion.dart
- lib/ui/screens/home/components/card_home.dart
- lib/ui/screens/home/components/card_video.dart
- lib/ui/screens/home/components/statistics_button.dart
- lib/ui/screens/home/home_page.dart
- lib/ui/screens/initiatives/initiatives_page.dart
- lib/ui/screens/measures/measures_extensions.dart
- lib/ui/screens/measures/measures_page.dart
- lib/ui/screens/splash/splash_page.dart
- lib/ui/screens/statistics/statistics_page.dart
- lib/ui/widgets/initiatives_item.dart
Closes #195 and #193 
- reduced Size box under the logo to 8
- Bump Size box to 16 below Slider
- Add click feedback on Stats red card
- Changed OverlayStatus Bar color on Android to Background White and Black text
- Initiatives change padding
- Initiatives change hit row size
- Initiatives change TextStyle for titles
✅ All tests passed
✅ dartfmt @ root
> Home UI fixes and initiatives page

- lib/model/post_type.dart
Updates Measures and Initiatives to PRD endpoints.
Closes #202.
> Change PRD Endpoints (#202)

- lib/ui/screens/faqs_details/faq_details_page.dart
- lib/ui/screens/initiatives/initiatives_page.dart
closes #205
closes #207
* Faqs UI is the same as Initiatives
* Added Padding to last item
**Screenshots**
* Faqs:
* Last Item
> Change Faqs and Initiatives

- lib/model/post_type.dart
closes #206 
**Description** 
* Adds category 5 to measures endpoint so that it returns the important and normal measures
> #206 Update Measure Endpoint

- lib/generated/intl/messages_all.dart
- lib/generated/intl/messages_en.dart
- lib/generated/l10n.dart
- lib/l10n/intl_en.arb
- lib/resources/style/themes.dart
- lib/ui/app.dart
WIP for #214 
- Fix for Licenses text theme
Missing:
- The title is not assuming the related translation
> fix licenses page text theme color

- lib/ui/screens/faqs_details/faq_details_page.dart
- lib/ui/screens/home/components/card_home_slider.dart
Closes #215 
**Changes** 
✅ Add a white background to Sliders
✅ Remove `onExpansionChanged` from List Detail of FAQs
✅ dartfmt @ root
> Fix not showing FAQ when list too long

- README.md
Adds reference to project's wiki.
Closes #44.
> Update README (#44)

- lib/ui/screens/video_player/video_player_page.dart
closes #233 
**Description:**
* Adds new actions to video - only seekbar and progress
> Removes full screen option from video player

- lib/ui/screens/home/components/card_home_slider.dart
- lib/ui/screens/home/components/card_home_slider_indicator.dart
- lib/ui/screens/home/home_page.dart
- test/widget/home_card_slider_test.dart
Closes #238  #224 #226 
- Adds Auto Slide play running every 30s
- Adds Side cards
- Fixes all green on start
- Adds Widget Home card Tests
✅ All tests passed
✅ dartfmt @ root
> Slider autoplay and fixes
